project_id = "hvwovrurvleityqyshqv"

[functions.submit-baufinanzierung-webhook]
verify_jwt = false

[functions.submit-selbstauskunft-webhook]
verify_jwt = false

[functions.verify-prognose-documents]
verify_jwt = false
